### ISSUE TITLE
Not working in test mode?

### ISSUE THREAD

**Issue by WTK** [PaulGilmartin/django-queryhunter#2]
I've tried to configure queryhunter in number of ways to make it work while running tests (using django test runner and pytest). Nothing seems to work, queries aren't captured neither in console nor in the log file. 

What's the right way to use it? Does it even work while running tests?

**Comment by PaulGilmartin** [comment]
@WTK I have had it work fine whilst running the unit tests in the source code (/queryhunter/tests) and in other projects. I have used both pytest and the django test runner and both times it logged/printed as I would have expected. 

Maybe you could tell me more about your setup/configuration so I could try to assist further?

**Comment by WTK** [comment]
> @WTK I have had it work fine whilst running the unit tests in the source code (/queryhunter/tests) and in other projects. I have used both pytest and the django test runner and both times it logged/printed as I would have expected.
> 
> Maybe you could tell me more about your setup/configuration so I could try to assist further?

Thanks for a quick reply. I'll review my setup again, if it should work then clearly there's something wrong on my side. I'll check and let you know in case can't figure it out. Cheers!
